manifest:
  remotes:
    - name: nofilter
      url-base: https://github.com/NoFilterA1
  projects:
    - name: zmk
      remote: nofilter
      repo-path: rgb-nzmk
      revision: zmk-perkey_ug
      import: app/west.yml
  self:
    path: config
