manifest:
  remotes:
    - name: nofilter
      url-base: https://github.com/NoFilterA1
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: nofilter
      repo-path: rgb-nzmk
      revision: zmk-perkey_ug
      import: app/west.yml
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
  self:
    path: config
